### ISSUE TITLE
Add download feature for badge

### ISSUE THREAD

**Issue by errorinc0de** [GDSC-RCCIIT/gdsc-badge-generator#1]
Exported file type should be of .jpg or .png

**Comment by Subham-dury** [comment]
Can I work on this issue and add the feature?

**Comment by codenarocode** [comment]
I would like to add this feature

**Comment by OBITORASU** [comment]
I will assign this issue to @Subham-dury since he was the first one to ask.

**Comment by errorinc0de** [comment]
Issue resolved by PR #5 by @Subham-dury
