### ISSUE TITLE
Change The Card name as I input

### ISSUE THREAD

**Issue by bartick** [GDSC-RCCIIT/gdsc-badge-generator#14]
## Suggest an improvement for a script
If p tag text on the badge changes as I type in the input field will be bettter I think

### Mention the Script where you would like to have this feature added
index.html

### Is your feature request related to a problem? Please describe
There is no problem with the current implementation but users on mobile might forget to click enter for the change to happen.

### Describe the solution you'd like
There should be one simple change of event listener but the current js implementation should work with the new event.

## Do you want to work on this?
- [ ] yes
- [ ] no
- [x] Maybe, I would love to work on this. But maintainers are free to assign it to someone else if they feel like it.

**Comment by Swagnik02** [comment]
i would like to work on it.............

participating hacktoberfest 2k21.

**Comment by errorinc0de** [comment]
Assigned you the issue @Swagnik02
