### ISSUE TITLE
Add gdsc logo to website icon..

### ISSUE THREAD

**Issue by codenarocode** [GDSC-RCCIIT/gdsc-badge-generator#3]
## Suggest an improvement for a script
Add GDSC logo to website icon

## Do you want to work on this?
- [ ] yes
- [ ] no

**Comment by codenarocode** [comment]
Can i add gdsc logo to website icon?

**Comment by codenarocode** [comment]
Please respond!! @OBITORASU  @errorinc0de

**Comment by OBITORASU** [comment]
I am not the maintainer of this repository but I will have one of the maintainers look into it just hold on. Thanks :)

**Comment by errorinc0de** [comment]
Assigned you the issue, you may work on it.
@codenarocode
