### ISSUE TITLE
Add a navigation bar

### ISSUE THREAD

**Issue by bartick** [GDSC-RCCIIT/gdsc-badge-generator#4]
## Suggest an improvement for a script
A navigation bar to navigate to different gdsc-rcciit websites including its social media handles.

### Mention the Script where you would like to have this feature added
index.html

### Describe alternatives you've considered
I can also considered adding a footer rather than adding a nav bar. But I think nav bar will make the website stand out rather than a footer without navbar

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by deagleSC** [comment]
Great idea, @bartick. You can add links to other GDSC-related websites on the nav, and socials on a footer. Keep the styles coherent with the official GDSC RCCIIT Website. Go ahead.
