### ISSUE TITLE
Rounded corners not retained on Image download - Fix needed

### ISSUE THREAD

**Issue by deagleSC** [GDSC-RCCIIT/gdsc-badge-generator#9]
### Mention the script affected by the bug
Name of the affected script: [main.js](https://github.com/GDSC-RCCIIT/gdsc-badge-generator/blob/master/main.js)

### Describe the bug
The rounded corners in the preview while customization of the badge is not retained after downloading the image in PNG or JPG format.

### To Reproduce
Ex. Steps to reproduce the behavior:
1. Go to index.html.
2. Enter your Name and Photo.
3. Click on Download.
4. View Downloaded Photo.
5. See error.

### Expected behavior
On downloading the Image in PNG or JPG formats, the rounded corners should be retained in the final image as visible in the preview.

### Screenshots
![Supratik Chakraborty](https://user-images.githubusercontent.com/66419293/135703966-885e3ab9-98fb-4233-9960-c0994d319123.png)

### Device Information (please complete the following information):
 - OS: [Windows]
 - Browser [Google Chrome]

## Do you want to work on this?
- [ ] yes
- [ ] no

**Comment by shikhar13012001** [comment]
Can I work on this issue ?
Please assign this to me

**Comment by deagleSC** [comment]
Go ahead, @shikhar13012001.

**Comment by errorinc0de** [comment]
Fixed by #12
